<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--

    Copyright (C) 2017 Red Hat, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.atlasmap</groupId>
    <artifactId>atlas-parent</artifactId>
    <version>2.6.0-SNAPSHOT</version>
    <relativePath>../../parent</relativePath>
  </parent>

  <artifactId>atlasmap-embedded-sample</artifactId>
  <name>Embedded AtlasMap sample app</name>
  <description>Minimal Spring Boot runtime hosting AtlasMap services for an embedded UI</description>
  <packaging>jar</packaging>

  <properties>
    <failOnMissingWebXml>false</failOnMissingWebXml>
    <maven.build.timestamp.format>yyyy-MM-dd HH:mm</maven.build.timestamp.format>
  </properties>

  <build>
    <finalName>atlasmap-embedded-sample</finalName>

    <plugins>
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>unpack-ui</id>
            <phase>process-resources</phase>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>io.atlasmap</groupId>
                  <artifactId>atlasmap-ui</artifactId>
                  <classifier>mock-embedded</classifier>
                  <type>zip</type>
                  <outputDirectory>${project.build.directory}/classes/public</outputDirectory>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <jvmArguments>-server -Xms256m -Xmx1024m</jvmArguments>
          <mainClass>io.atlasmap.embedded.Application</mainClass>
        </configuration>
        <executions>
          <execution>
            <id>repackage</id>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
          <execution>
            <id>build-info</id>
            <goals>
              <goal>build-info</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <systemPropertyVariables>
            <webdriver.chrome.driver>${webdriver.chrome.driver}</webdriver.chrome.driver>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>

    <dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>atlas-java-module</artifactId>
    </dependency>
    <dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>atlas-java-service</artifactId>
    </dependency>
    <dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>atlas-json-module</artifactId>
    </dependency>
    <dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>atlas-json-service</artifactId>
    </dependency>
    <dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>atlas-xml-module</artifactId>
    </dependency>
    <dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>atlas-xml-service</artifactId>
    </dependency>
    <dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>atlas-csv-module</artifactId>
    </dependency>
    <dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>atlas-csv-service</artifactId>
    </dependency>
    <dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>atlas-dfdl-module</artifactId>
    </dependency>
    <dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>atlas-dfdl-service</artifactId>
    </dependency>
    <dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>atlas-service</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-websocket</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-tomcat</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-undertow</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-websocket</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-multipart-provider</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
